### ISSUE TITLE
[winewayland] MangoHud cannot be controlled with shortcut keys

### ISSUE THREAD

**Issue by llitz** [Etaash-mathamsetty/Proton#53]
For apps launched with mangohud under winewayland mode, the shortcuts for controlling mangohud do not seem to work:

Shift_L+F4 - reload config
Shift_R+F12 - toggle mangohud ui display
Shift_R+F10 - change position of ui

Changing them to custom keybind also didn't work, as it could've been a matter of interpreting the Shift Keys. Keys tried (they all work with the x11 driver):

XF86Launch6
XF86Launch7
XF86Launch8
XF86Launch9
a
b
C
D

The test has been performed with 2 games - GuildWars 2 and Remnandt 2. Both games exhibit the exact same behavior - with X11 driver (XWayland) mangohud can be controlled without issues, with wayland natively running, mangohud doesn't receive any of the shortcuts

P.S.: Thanks for the extensive work on this, I have been closely trying a few releases every now and then and the last one seems really usable.

**Comment by Etaash-mathamsetty** [comment]
I've fixed this a long time ago fwiw, use mangohud-git.

**Comment by llitz** [comment]
> I've fixed this a long time ago fwiw, use mangohud-git.

@Etaash-mathamsetty hmmm am I missing something? I am running the latest version from the git repository - [ff6e595](https://github.com/flightlessmango/MangoHud/commit/ff6e5954ea7e340d9bb4509754babf0db1b7c431) and it still doesn't work for me

Edit: nvm, I think it is forcefully using some libMangoHud.so from somewhere else

**Comment by Etaash-mathamsetty** [comment]
> > I've fixed this a long time ago fwiw, use mangohud-git.
> 
> @Etaash-mathamsetty hmmm am I missing something? I am running the latest version from the git repository - [ff6e595](https://github.com/flightlessmango/MangoHud/commit/ff6e5954ea7e340d9bb4509754babf0db1b7c431) and it still doesn't work for me
> 
> Edit: nvm, I think it is forcefully using some libMangoHud.so from somewhere else

Make sure your vulkan layers are configured properly and it should load from the right place and just work :)

**Comment by llitz** [comment]
> > > I've fixed this a long time ago fwiw, use mangohud-git.
> > 
> > 
> > [@Etaash-mathamsetty](https://github.com/Etaash-mathamsetty) hmmm am I missing something? I am running the latest version from the git repository - [ff6e595](https://github.com/flightlessmango/MangoHud/commit/ff6e5954ea7e340d9bb4509754babf0db1b7c431) and it still doesn't work for me
> > Edit: nvm, I think it is forcefully using some libMangoHud.so from somewhere else
> 
> Make sure your vulkan layers are configured properly and it should load from the right place and just work :)

Somehow I ended with an old copy of the mangohud stuck somewhere else, it wasn't the .so file at all. I only realized it after I added version to the preset and saw it still said 0.7.2.

Thanks for taking the time to answer!
